apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  jane-reader
subjects:
  - kind: User
    name: jane # matches the CN in the certificate
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
